apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
    - image: guestbook-backend
      context: guestbook/src/backend
    - image: guestbook-frontend
      context: guestbook/src/frontend
    - image: webapp-frontend
      context: webapp/
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
      - kubernetes-manifests/**
profiles:
  - name: gke-non-prod-guestbook 
    build:
      artifacts:
      - image: asia.gcr.io/developer-experience-239623/guestbook-backend
        context: guestbook/src/backend
      - image: asia.gcr.io/developer-experience-239623/guestbook-frontend
        context: guestbook/src/frontend
      googleCloudBuild:
        projectId: developer-experience-239623
    deploy:
      kustomize:
        path: ./guestbook/resources/overlays/non-production
  - name: gke-prod-guestbook 
    build:
      artifacts:
      - image: asia.gcr.io/developer-experience-239623/guestbook-backend
        context: guestbook/src/backend
      - image: asia.gcr.io/developer-experience-239623/guestbook-frontend
        context: guestbook/src/frontend
      googleCloudBuild:
        projectId: developer-experience-239623
    deploy:
      kustomize:
        path: ./guestbook/resources/overlays/production
  - name: local-guestbook 
    build:
      artifacts:
      - image: guestbook-backend
        context: guestbook/src/backend
      - image: guestbook-frontend
        context: guestbook/src/frontend
    deploy:
      kustomize:
        path: ./guestbook/resources/overlays/local
