apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: webapp
    tier: frontend
  ports:
  - port: 8080
    targetPort: http-server
