apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: webapp
    tier: frontend
  ports:
  - port: 80
    targetPort: http-server
---
# apiVersion: apps/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
    tier: frontend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      tier: frontend
  template:
    metadata:
      labels:
        app: webapp
        tier: frontend
    spec:
      containers:
      - name: webapp
        # image: host.docker.local:5000/dev-xp/webapp
        image: registry.kube-system.svc.cluster.local:80/dev-xp/webapp
        ports:
        - name: http-server
          containerPort: 8080
